In [6]:
import pandas as pd


players = pd.read_parquet('data/players.parquet')

years_to_process = ['2020', '2021', '2022', '2023']
plays = None
for year in years_to_process:
    path = f'data/play_by_play_{year}.parquet'
    tmp_plays = pd.read_parquet(path)
    plays = pd.concat([plays, tmp_plays])

In [16]:
active_players = players.loc[players['status'] == 'ACT']

In [17]:
plays

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
0,1.0,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,None,None,None,...,0.0,1.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,39.0,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,SF,home,ARI,...,0.0,1.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,54.0,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,SF,home,ARI,...,0.0,1.0,1.294838,0.503370,4.275047,2.0,0.619306,0.239695,0.515058,48.494154
3,93.0,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,SF,home,ARI,...,0.0,1.0,0.857214,NaN,NaN,NaN,NaN,NaN,0.413357,-41.335732
4,118.0,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,SF,home,ARI,...,0.0,1.0,-0.454665,NaN,NaN,NaN,NaN,NaN,0.446920,-44.692025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49660,4791.0,2023_22_SF_KC,2024021100,KC,SF,POST,22,KC,home,SF,...,0.0,0.0,1.728891,NaN,NaN,NaN,NaN,NaN,0.182589,81.741054
49661,4813.0,2023_22_SF_KC,2024021100,KC,SF,POST,22,KC,home,SF,...,0.0,0.0,-0.330699,NaN,NaN,NaN,NaN,NaN,0.310144,-31.014398
49662,4835.0,2023_22_SF_KC,2024021100,KC,SF,POST,22,KC,home,SF,...,0.0,0.0,-0.637115,1.315985,6.498790,6.0,0.428395,0.361828,0.600400,39.959973
49663,4860.0,2023_22_SF_KC,2024021100,KC,SF,POST,22,KC,home,SF,...,0.0,0.0,3.102806,1.780787,0.772520,1.0,0.993362,0.784198,0.623245,37.675518
49664,4881.0,2023_22_SF_KC,2024021100,KC,SF,POST,22,KC,home,SF,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
# trim down columns
fantasy_plays = plays[['game_id', 'passer', 'passer_id', 'rusher', 'rusher_id', 'receiver', 'receiver_id', 'pass', 'rush', 'yards_gained', 'fumble', 'touchdown', 'pass_touchdown', 'rush_touchdown', 'rush_attempt', 'pass_attempt', 'yards_after_catch']]

In [26]:
# filter down to records we care about

filtered_plays = fantasy_plays.dropna(subset=['passer', 'rusher', 'receiver'], how='all')
filtered_plays

,game_id,passer,passer_id,rusher,rusher_id,receiver,receiver_id,pass,rush,yards_gained,fumble,touchdown,pass_touchdown,rush_touchdown,rush_attempt,pass_attempt,yards_after_catch
2,2020_01_ARI_SF,J.Garoppolo,00-0031345,None,None,G.Kittle,00-0033288,1.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
3,2020_01_ARI_SF,None,None,R.Mostert,00-0031687,None,None,0.0,1.0,14.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN
4,2020_01_ARI_SF,None,None,R.Mostert,00-0031687,None,None,0.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN
5,2020_01_ARI_SF,None,None,R.Mostert,00-0031687,None,None,0.0,1.0,-6.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN
6,2020_01_ARI_SF,J.Garoppolo,00-0031345,None,None,G.Kittle,00-0033288,1.0,0.0,11.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49659,2023_22_SF_KC,P.Mahomes,00-0033873,None,None,I.Pacheco,00-0037197,1.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,1.0,9.0
49660,2023_22_SF_KC,P.Mahomes,00-0033873,None,None,None,None,1.0,0.0,19.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN
49661,2023_22_SF_KC,None,None,I.Pacheco,00-0037197,None,None,0.0,1.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN
49662,2023_22_SF_KC,P.Mahomes,00-0033873,None,None,T.Kelce,00-0030506,1.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,1.0,9.0
49663,2023_22_SF_KC,P.Mahomes,00-0033873,None,None,M.Hardman,00-0035140,1.0,0.0,3.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0

In [43]:
# aggregate to a game level / player level
game_agg = filtered_plays.groupby(['game_id', 'passer', 'passer_id', 'rusher', 'rusher_id', 'receiver', 'receiver_id']) \
                         .sum()

In [41]:
game_agg

Empty DataFrame
Columns: [pass, rush, yards_gained, fumble, touchdown, pass_touchdown, rush_touchdown, rush_attempt, pass_attempt, yards_after_catch]
Index: []